language: java

jdk:
  - oraclejdk8
  
install: true

script: 
- mvn -f RiskBoardGame/pom.xml test
- "mvn -f RiskBoardGame/pom.xml cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
